[General]

# Fake-IP + TUN混合
EN_MODE = fake-ip-mix

# 家庭旁路由 IPv6
IPV6_ENABLE = 1
IPV6_DNS = 0

# 模块更新后重启 OpenClash
RESTART = true


[YAML]

# 家里需要局域网设备连接旁路由
allow-lan: true
bind-address: '*'

# OpenWrt给局域网设备提供DNS
dns:
  listen: 0.0.0.0:1053
